#+BEGIN_COMMENT
/Lag dine egne dataspill/\\
Copyright (C) 2015 Sigmund Hansen

Denne boka og koden som inngår i den, er fri; du kan redistribuere den
og/eller endre den etter vilkårne i GNU General Public License som
publisert av Free Software Foundation, enten versjon 3 av lisensen,
eller (som du ønsker) enhver senere versjon.

Denne boka er distribuert i håp om at den skal være nyttig, men UTEN
NOEN GARANTI; selv uten noen antydet garanti om SALGBARHET eller
EGNETHET FOR NOE BESTEMT FORMÅL. Se GNU General Public License for mer
detaljer.

Du skal ha mottatt en kopi av GNU General Public License med denne
boka. Hvis ikke, se <http://www.gnu.org/licenses/>.
#+END_COMMENT

* Kongen befaler

I dette kapitlet skal vi lage et spill som heter /Kongen befaler/,
basert på spillet /Simon/ . Spillet går ut på at det spilles en melodi,
og spilleren må prøve å huske melodien og spille denne. Vi begynner
med dette spillet fordi det dekker mye av det grunnleggende, uten at
det er så vanskelig å komme igang med.

I spillet har vi et antall knapper som hver spiller sin tone. Knappen
skal lyse når tonen spilles, slik at man kan spille det både med og
uten lyd. I den varianten vi lager her, bruker vi fire knapper, og
altså fire toner, men man kan ta med flere knapper og toner for å
gjøre spillet vanskeligere.

** Knapper og musetrykk

Vi skal ha med fire knapper i spillet for å spille de forskjellige
tonene. Derfor må vi ha med kode for å tegne opp knappene og for å ta
imot musetrykk. Vi begynner med en enkel løsning der knappene dekker
hele vinduet:

#+NAME: lst:konge-1
#+CAPTION: Første utkast til knapper.
#+BEGIN_SRC processing
/*
 * Her setter vi opp vinduet
 * og andre ting som må forberedes før spillet kjører.
 */
void setup() {
  size(600, 600);
}

/*
 * Her tegner vi opp knappene.
 */
void draw() {
  background(0);
  fill(0, 0, 255);
  rect(0, 0, width / 2, height / 2);
  fill(0, 255, 0);
  rect(width / 2, 0, width, height / 2);
  fill(255, 255, 0);
  rect(0, height / 2, width / 2, height);
  fill(255, 0, 0);
  rect(width / 2, height / 2, width, height);
}
#+END_SRC

Denne koden består av flere deler, og vi skal nå se på hva hver av
disse gjør. Aller først i programmet ser vi en kommentar. Dette er
tekst som ikke tas med som kode når programmet kjøres. Kommentarene
her starter med [[ltx:pde][/*]] og slutter med [[ltx:pde][*/]], alt som kommer imellom disse
blir ignorert av Processing når programmet kjøres.

Rett etter kommentaren ser vi linjen [[ltx:pde][void setup() {]] som er starten på
en funksjon, setup, som skal være med i stort sett alle
Processing-programmer. Koden som kommer mellom krøllparentesene,
utgjør koden i funksjoneen og kalles kroppen til funksjonen. Den
eneste linjen i kroppen, [[ltx:pde][size(600, 600);]], angir at programmet skal
kjøre i et vindu som er 600 piksler bredt og 600 piksler høyt. Linjen
etter består av en krøllparentes som markerer slutten på funksjonen.
